"""
Results reporting — export evaluation results in various formats.

TODO:
- [ ] HTML report with interactive charts
- [ ] PDF report generation
- [ ] W&B / MLflow integration
- [ ] Slack/Discord notification of results
- [ ] Historical comparison (regression detection)
"""

import json
import os
from pathlib import Path
from datetime import datetime
from typing import List, Optional


class Reporter:
    """Generate reports from evaluation results."""

    def __init__(self, results_dir: str | None = None):
        self.results_dir = Path(results_dir or os.getenv("EVALFORGE_RESULTS_DIR", "./results"))

    def save_run(self, run_data: dict, run_id: Optional[str] = None) -> str:
        """
        Save an evaluation run to disk.

        Args:
            run_data: Full evaluation run data.
            run_id: Optional run identifier. Auto-generated if not provided.

        Returns:
            The run ID.
        """
        self.results_dir.mkdir(parents=True, exist_ok=True)

        if run_id is None:
            run_id = datetime.now().strftime("%Y%m%d_%H%M%S")

        path = self.results_dir / f"{run_id}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(run_data, f, indent=2, ensure_ascii=False)

        return run_id

    def load_run(self, run_id: str) -> dict:
        """Load a previous evaluation run."""
        path = self.results_dir / f"{run_id}.json"
        if not path.exists():
            raise FileNotFoundError(f"Run {run_id} not found at {path}")

        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    def export_html(self, run_id: str, output_path: Optional[str] = None) -> str:
        """
        Generate an HTML report for a run.

        TODO: Implement proper HTML template with charts.
        Currently placeholder.
        """
        data = self.load_run(run_id)

        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>EvalForge Report — {run_id}</title>
    <style>
        body {{ font-family: system-ui, sans-serif; max-width: 800px; margin: 2em auto; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #f5f5f5; }}
        .score-high {{ color: green; }}
        .score-mid {{ color: orange; }}
        .score-low {{ color: red; }}
    </style>
</head>
<body>
    <h1>EvalForge Report</h1>
    <p>Run ID: {run_id}</p>
    <p>Benchmark: {data.get('benchmark', 'N/A')}</p>
    <p>Models: {', '.join(data.get('models', []))}</p>
    <p>Prompts: {data.get('num_prompts', 0)}</p>

    <h2>Results</h2>
    <p><em>Detailed results coming in v0.4.0</em></p>
    <p>For now, export as JSON for programmatic analysis.</p>

    <footer>
        <p>Generated by <a href="https://github.com/Nhaked-try/evalforge">EvalForge</a></p>
    </footer>
</body>
</html>"""

        output_path = Path(output_path or self.results_dir / f"{run_id}.html")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(html)

        return str(output_path)


def list_runs() -> list[dict]:
    """List all evaluation runs."""
    results_dir = Path(os.getenv("EVALFORGE_RESULTS_DIR", "./results"))
    if not results_dir.exists():
        return []

    runs = []
    for f in sorted(results_dir.glob("*.json"), reverse=True):
        try:
            with open(f) as fp:
                data = json.load(fp)
            runs.append({
                "id": f.stem,
                "benchmark": data.get("benchmark", "unknown"),
                "models": ", ".join(data.get("models", [])),
                "date": datetime.fromtimestamp(f.stat().st_mtime).strftime("%Y-%m-%d %H:%M"),
            })
        except Exception:
            continue

    return runs
